"""Build the thesis as LaTeX via the AITU memoir template + tectonic.

Pipeline:
1. Convert each `0N_*.md` source to a LaTeX fragment via pypandoc with
   `--top-level-division=chapter`.
2. Wire the fragments into the AITU template (`thesis/latex/`) by overwriting:
   - `frontmatter/title.tex`
   - `frontmatter/abstract.tex`
   - `frontmatter/intro.tex` (the standalone Introduction chapter)
   - `frontmatter/concl.tex` (Conclusion)
   - `chapters/chapter01/introduction.tex`
   - `chapters/chapter02/main.tex`
   - `chapters/chapter03/conclusion.tex`
   - `chapters/appendices/references.tex`
3. Write a simplified driver `thesis_main.tex` that uses the AITU memoir
   preamble but only imports our content (skips placeholder dedication /
   declaration / definitions / dda blocks).
4. Run `tectonic` on `thesis_main.tex` to produce `thesis_main.pdf`.

Usage:
    venv\\Scripts\\python.exe thesis\\build_latex.py
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

import pypandoc

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

HERE = Path(__file__).parent
LATEX = HERE / "latex"
TECTONIC = Path.home() / ".local" / "bin" / "tectonic.exe"

# Map of @bibkey -> reference number (mirrors build.py CITATIONS).
# Numbered in order of first citation in the slim thesis body, with uncited
# entries removed (regenerated by _audit_tmp/renumber_refs.py from the @keys in
# 02..06 + 07_references.md). Keep this in sync if citations are added/removed.
CITATIONS: dict[str, int] = {
    "Dakov2024": 1, "SofiaDeepForest2024": 1, "DeepForest2019": 2,
    "AbbasYOLO2025": 3, "Lv2023": 4, "LvMCAN2023": 4, "Branson2019": 5,
    "Schmohl2022": 6, "Martins2021": 7, "Martins2021Species": 7,
    "dosSantos2019": 8, "VelasquezCamacho2023": 9, "He2022": 10,
    "VelasquezCamacho2025": 11, "Xia2021": 12, "Ventura2024": 13,
    "Xu2025": 14, "Awad2021": 15, "FasterRCNN2015": 16, "MaskRCNN2017": 17,
    "YOLOv1": 18, "UltralyticsYOLO2023": 19, "Sun2025": 20,
    "RetinaNet2017": 21, "SAM2023": 22, "SAM2024": 22, "Ravi2024": 23,
    "SAM2_2024": 23, "Zheng2022": 24, "Wang2021": 25, "He2020": 26,
    "Zhang2022": 27, "Zhang2024": 28, "Chen2022": 29, "Chen2023": 30,
    "Huerta2021": 31, "Timilsina2020": 32, "Chen2021": 33, "Dong2019": 34,
    "WBF2021": 35,
}

CITE_GROUP_RE = re.compile(r"\[((?:@[A-Za-z0-9_]+(?:\s*;\s*)?)+)\]")
SINGLE_CITE_RE = re.compile(r"@([A-Za-z0-9_]+)")


def replace_citations(text: str) -> str:
    def sub(m: re.Match) -> str:
        nums = []
        for key in (sk.group(1) for sk in SINGLE_CITE_RE.finditer(m.group(1))):
            nums.append(str(CITATIONS.get(key, "?")))
        return "[" + ", ".join(nums) + "]"
    return CITE_GROUP_RE.sub(sub, text)


def md_to_latex(md_text: str) -> str:
    """Run pypandoc, return LaTeX body.

    `--wrap=none` is required: pandoc's default wrapping can split inline
    `\\textbf{...}` spans across paragraph breaks when the bold text contains
    multi-byte Unicode (e.g. Cyrillic / Kazakh), which makes the output
    LaTeX-invalid (a `\\text@command` argument cannot cross a paragraph end).

    After conversion we post-process the result to collapse blank lines
    inside `\\begin{longtable}...\\end{longtable}` column specs — pandoc still
    emits blank paragraphs between column lines in the table preamble, which
    breaks LaTeX (the longtable column-spec argument cannot contain `\\par`).
    """
    tex = pypandoc.convert_text(
        md_text, "latex", format="md",
        extra_args=["--top-level-division=chapter", "--wrap=none"],
    )

    # Collapse blank lines inside every longtable environment. Pandoc still
    # emits blank paragraphs between column-spec lines in the table preamble,
    # which breaks LaTeX. We do a line-by-line scan instead of a single regex
    # for robustness against nested braces.
    out_lines: list[str] = []
    inside = 0
    for line in tex.splitlines():
        stripped = line.strip()
        if stripped.startswith("\\begin{longtable}"):
            inside += 1
        # drop empty lines while inside a longtable
        if inside > 0 and stripped == "":
            continue
        out_lines.append(line)
        if stripped.startswith("\\end{longtable}"):
            inside = max(0, inside - 1)
    tex = "\n".join(out_lines) + "\n"

    # Strip the explicit `Chapter N.` / `N.M[.K]` numbering that we ship in the
    # Markdown headings. LaTeX/memoir auto-numbers sections within each chapter,
    # so leaving the explicit numbers in produces double-numbering like
    # "Chapter 3. Chapter 3." or "3.3.5 3.3.5". The reference text in the body
    # ("see Section 3.2.3") is intentionally left as plain text.
    tex = re.sub(
        r"\\chapter\{Chapter\s+\d+\.\s*(.+?)\}",
        r"\\chapter{\1}", tex,
    )
    tex = re.sub(
        r"\\(section|subsection|subsubsection|paragraph)\{(?:\d+(?:\.\d+)*\.?)\s+(.+?)\}",
        r"\\\1{\2}", tex,
    )

    # Pandoc emits longtables with equal-width p{...} columns regardless of
    # content. The result is that 2-character cells get the same width as
    # 50-character cells — model names wrap awkwardly while short numerics
    # have wasted space. Replace pandoc's auto-width spec with a content-
    # aware allocation: first column wider (row label), middle columns auto
    # (`l`), last column flexible (`p{}`) for notes/comments. Also strip the
    # `\begin{minipage}` wrappers pandoc adds around every header cell —
    # they add awkward vertical padding without contributing to the layout.
    tex = _fix_longtable_styles(tex)

    tex = _caption_longtables(tex)

    tex = _number_display_equations(tex)

    return tex


def _caption_longtables(latex: str) -> str:
    r"""Turn a bold caption paragraph that precedes a longtable
    (`\textbf{Table N --- ...}`) into a real \caption{} attached to the
    longtable, so the table appears in \listoftables with an auto number.

    Pandoc renders our markdown table captions as an ordinary bold paragraph
    above the table and gives the longtable no \caption, so \listoftables is
    empty and the manual "Table 2.1" numbers (which repeat) are never checked
    by LaTeX. We strip the manual "Table N --- " prefix, keep the descriptive
    text as the float caption, and let LaTeX number it (\caption -> LoT entry).
    longtable's own \caption produces a LoT line and an in-text "Table X:".
    """
    # Pandoc structure for a captionless markdown table is:
    #   \textbf{Table N --- <caption text>}
    #
    #   {\def\LTcaptype{none} % do not increment counter
    #   \begin{longtable}[]{@{}<spec>@{}}
    #   ...
    #   \end{longtable}
    #   }
    # The `\LTcaptype{none}` wrapper deliberately suppresses numbering/caption.
    # We remove that wrapper and inject a real \caption{} as the longtable's
    # first row, so LaTeX numbers the table and lists it in \listoftables.
    cap_re = re.compile(
        r"\\textbf\{Table[~ ]+[\d.]+[ ]*(?:---|--|—|-|:)[ ]*(.+?)\}\s*"
        r"\{\\def\\LTcaptype\{none\}[^\n]*\n"
        r"(\\begin\{longtable\}\[\]\{@\{\}.*?@\{\}\})"
        r"(.*?\\end\{longtable\})\s*"
        r"\}",
        re.DOTALL,
    )

    def repl(m: re.Match) -> str:
        caption = m.group(1).strip().rstrip(".")
        open_tbl = m.group(2)
        body_and_end = m.group(3)
        # \caption + \endfirsthead so the caption (and its LoT entry) appears
        # only on the FIRST page of a multi-page longtable; continuation pages
        # would otherwise repeat the caption and emit a duplicate LoT line.
        return (open_tbl + "\n\\caption{" + caption + "}\\\\\n\\endfirsthead\n"
                + body_and_end)

    return cap_re.sub(repl, latex)


def _number_display_equations(latex: str) -> str:
    r"""Convert pandoc's unnumbered display math \[ ... \] into numbered
    equation environments, so display formulas carry (chapter.n) numbers like
    the AITU reference diploma. Pandoc renders markdown $$...$$ as

        \[
        ... \]

    We replace each such block with \begin{equation} ... \end{equation}.
    Inline math \( ... \) and already-numbered environments are left untouched.
    """
    # Non-greedy match of a top-level \[ ... \] block. Pandoc never nests these.
    eq_re = re.compile(r"\\\[(.+?)\\\]", re.DOTALL)

    def repl(m: re.Match) -> str:
        body = m.group(1).strip()
        # Skip if it already contains an alignment/equation environment.
        if "\\begin{" in body:
            return m.group(0)
        return "\\begin{equation}\n" + body + "\n\\end{equation}"

    return eq_re.sub(repl, latex)


def _fix_longtable_styles(latex: str) -> str:
    """Rework pandoc's verbose longtable column specs into content-aware
    p{} widths. Pandoc's default behaviour is to give every column an equal
    1/N share of the typeblock, which makes long-text cells wrap awkwardly
    while short cells waste horizontal space. We scan the table body, find
    the longest cell per column, and allocate widths proportional to those
    maxima — clamped to a [6%, 45%] range and renormalised to 92% of
    \\linewidth so tabcolseps fit comfortably."""

    # First strip the minipage wrapper that pandoc adds around every header
    # cell. We do this BEFORE width allocation so the header content is part
    # of the per-column length statistics.
    latex = re.sub(
        r"\\begin\{minipage\}\[b\]\{\\linewidth\}\\raggedright\s*"
        r"(.+?)"
        r"\s*\\end\{minipage\}",
        lambda m: r"\textbf{" + m.group(1).strip() + r"}",
        latex,
        flags=re.DOTALL,
    )

    # Match a complete longtable environment so we can read its body to size
    # the columns. The non-greedy `(.+?)` between the opening brace and
    # `\end{longtable}` captures the column-header + body region.
    table_re = re.compile(
        r"(\\begin\{longtable\}\[\]\{@\{\}\s*"
        r"((?:>\{\\raggedright\\arraybackslash\}p\{\(\\linewidth - \d+\\tabcolsep\) \* \\real\{[\d.]+\}\}\s*)+)"
        r"@\{\}\})"
        r"(.+?)"
        r"(\\end\{longtable\})",
        re.DOTALL,
    )

    def _strip_for_length(cell: str) -> str:
        """Approximate the visual length of a LaTeX cell by stripping
        commands but keeping their arguments. \\textbf{X} -> X."""
        s = cell
        s = re.sub(r"\\(textbf|texttt|emph|textit|textsf|textsc)\{([^{}]*)\}", r"\2", s)
        s = re.sub(r"\\[a-zA-Z]+\*?\s*", "", s)  # drop remaining commands
        s = re.sub(r"\{|\}", "", s)
        return s.strip()

    def replace_table(m: re.Match) -> str:
        spec_block = m.group(2)
        body = m.group(3)
        n = len(re.findall(r"\\real\{([\d.]+)\}", spec_block))

        # Extract every row: rows end with `\\` followed by a newline. The
        # first row is the header; subsequent rows are the body.
        rows: list[list[str]] = []
        for raw_row in re.findall(r"(?<![\\&])((?:[^\\]|\\(?!\\))*?)\\\\(?:\s|$)", body):
            cells = raw_row.split("&")
            if len(cells) == n:
                rows.append([_strip_for_length(c) for c in cells])

        if not rows:
            even = round(0.92 / n, 3)
            specs = [rf"p{{{even}\linewidth}}" for _ in range(n)]
        else:
            # Strategy: treat the column header as a hard minimum-content
            # length (so the header never gets squeezed below its own text
            # width) and use body content as the "preferred" length. The
            # natural width of a column is then max(header, body) clamped to
            # a sensible range, and we allocate proportionally to natural
            # widths with a per-column floor so short columns still have room.
            header_row = rows[0]
            body_rows = rows[1:] if len(rows) > 1 else rows

            # Clamp header length to [4, 18] — headers above 18 chars are
            # rare and usually have spaces that can wrap onto a second line.
            header_chars = [max(4, min(18, len(c))) for c in header_row]
            # Clamp body content per cell to [4, 30] then take max per column.
            body_chars = [4] * n
            for row in body_rows:
                for i, cell in enumerate(row):
                    body_chars[i] = max(body_chars[i], min(30, len(cell)))
            # Natural width signal = max(header, body).
            natural = [max(h, b) for h, b in zip(header_chars, body_chars)]

            total = sum(natural)
            # Allocate within a typeblock budget that depends on N: wider
            # tables get a smaller budget so per-column floor still fits.
            budget = 0.95 if n <= 5 else 0.97
            raw_widths = [budget * c / total for c in natural]

            # Per-column floor — different for narrow vs wide tables.
            # For a 7-col table at floor=0.10 we'd need 0.70 just for floors,
            # which leaves no headroom for content variation — so the floor
            # is scaled down for wider tables.
            floor = {2: 0.25, 3: 0.15, 4: 0.12, 5: 0.10}.get(n, 0.09)
            widths = [max(floor, w) for w in raw_widths]

            # Renormalise so widths sum to `budget` without exceeding it.
            s = sum(widths)
            if s > budget:
                widths = [w * budget / s for w in widths]

            # Wrap each p{} in `>{\raggedright\arraybackslash}` so text is
            # left-aligned (ragged-right edge) instead of justified. Justified
            # cells try to stretch words to fill the line, and when a cell
            # contains a long unbreakable monospace identifier
            # (e.g. `confidence_threshold`, 20 chars), justification can
            # cause letters to overlap or run past the cell boundary.
            # Ragged-right gives LaTeX freedom to break wherever it can.
            specs = [
                rf">{{\raggedright\arraybackslash}}p{{{round(w, 3)}\linewidth}}"
                for w in widths
            ]

        new_open = r"\begin{longtable}[]{@{}" + " ".join(specs) + r"@{}}"

        # For wide tables (≥ 6 cols) wrap the whole longtable in `\small`
        # so the content fits without further width squeezing.
        if n >= 6:
            return r"{\small " + new_open + body + m.group(4) + "}"
        return new_open + body + m.group(4)

    return table_re.sub(replace_table, latex)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(HERE)}  ({len(content):,} chars)")


def _strip_chapter_header(latex: str, expected_title: str | None = None) -> str:
    """Pandoc emits `\\chapter{Title}\\label{...}` at the top. We sometimes
    want only the body when we control the chapter wrapper ourselves."""
    return re.sub(r"^\\chapter\{[^}]*\}\\label\{[^}]*\}\s*", "", latex,
                  count=1, flags=re.MULTILINE)


# ============ Frontmatter ============

def make_title_tex() -> str:
    """AITU-style title page (clean rules-around-title layout)."""
    return r"""%
% File: title.tex (generated by build_latex.py)
%
\begin{titlingpage}
\begin{SingleSpace}
\calccentering{\unitlength}
\begin{adjustwidth*}{\unitlength}{-\unitlength}
\vspace*{10mm}
\begin{center}
\rule[0.5ex]{\linewidth}{2pt}\vspace*{-\baselineskip}\vspace*{3.2pt}
\rule[0.5ex]{\linewidth}{1pt}\\[\baselineskip]
{
\linespread{1.6}\selectfont
{\HUGE Development of a Deep Learning Model for Automated Tree Recognition and Green Space Mapping in Urban Environments}\\[4mm]
}
\rule[0.5ex]{\linewidth}{1pt}\vspace*{-\baselineskip}\vspace{3.2pt}
\rule[0.5ex]{\linewidth}{2pt}\\
\vspace{6mm}
{\large By}\\
\vspace{5mm}
{\large\textsc{Totin Anuar,\\[2mm] Aidarkhanov Rasul,\\[2mm] Sharipov Berik}}\\
\vspace{8mm}
\includegraphics[width=3.6cm]{logos/AITU.png}\\
\vspace{5mm}
{\large School of Artificial Intelligence and Data Science\\
\textsc{Astana IT University}}\\
\vspace{18mm}
\begin{minipage}{9cm}
\centering{6B06101 --- Computer Science}\\[2mm]
\centering{Supervisor: Syndar Satbayev}
\end{minipage}\\
\vspace{16mm}
{\large\textsc{June 2026}}\\[2mm]
{\large\textsc{Astana}}
\vspace{10mm}
\end{center}
\end{adjustwidth*}
\end{SingleSpace}
\end{titlingpage}
"""


def make_abstract_tex(md: str) -> str:
    """Three-language abstract. Pandoc converts cleanly; we just wrap."""
    body = md_to_latex(replace_citations(md))
    # Pandoc emits three \chapter{Abstract}, \chapter{Аннотация},
    # \chapter{Аңдатпа} — we keep them, memoir handles non-numbered chapters
    # via \chapter* if needed, but a regular \chapter is fine for frontmatter.
    return body


def make_intro_tex(md: str) -> str:
    return md_to_latex(replace_citations(md))


def make_concl_tex(md: str) -> str:
    tex = md_to_latex(replace_citations(md))
    # Make conclusion unnumbered (not "Chapter 4")
    tex = re.sub(
        r"\\chapter\{Conclusion\}\\label\{conclusion\}",
        r"\\chapter*{Conclusion}\\addcontentsline{toc}{chapter}{Conclusion}\\markboth{Conclusion}{Conclusion}",
        tex, count=1,
    )
    return tex


# ============ Main chapters ============

def make_chapter_tex(md_path: Path) -> str:
    return md_to_latex(replace_citations(md_path.read_text(encoding="utf-8")))


# ============ References ============

def make_declaration_tex(md: str) -> str:
    return md_to_latex(md)


def make_acknowledgements_tex(md: str) -> str:
    """Dedication & acknowledgements — unnumbered, listed in the ToC."""
    body = md_to_latex(md)
    body = re.sub(r"\\chapter\{Acknowledgements\}\\label\{acknowledgements\}",
                  r"\\chapter*{Acknowledgements}\\addcontentsline{toc}{chapter}{Acknowledgements}\\markboth{Acknowledgements}{Acknowledgements}",
                  body, count=1)
    return body


def make_abbreviations_tex(md: str) -> str:
    """Designations & abbreviations — unnumbered, listed in the ToC."""
    body = md_to_latex(md)
    body = re.sub(r"\\chapter\{Designations and Abbreviations\}\\label\{designations-and-abbreviations\}",
                  r"\\chapter*{Designations and Abbreviations}\\addcontentsline{toc}{chapter}{Designations and Abbreviations}\\markboth{Designations and Abbreviations}{Designations and Abbreviations}",
                  body, count=1)
    return body


def make_definitions_tex(md: str) -> str:
    body = md_to_latex(md)
    body = re.sub(r"\\chapter\{Definitions\}\\label\{definitions\}",
                  r"\\chapter*{Definitions}\\addcontentsline{toc}{chapter}{Definitions}\\markboth{Definitions}{Definitions}",
                  body, count=1)
    return body


def make_references_tex(md: str) -> str:
    """Bibliography from 07_references.md. We do NOT use bibtex — we just emit
    a 'Bibliography' chapter with numbered entries (in citation order)."""
    body = md_to_latex(md)
    # Replace the auto-generated \chapter{Bibliography} (Pandoc gives it) with
    # \chapter* so it doesn't count in the chapter numbering; still ToC-listed.
    body = re.sub(r"\\chapter\{Bibliography\}\\label\{bibliography\}",
                  r"\\chapter*{Bibliography}\\addcontentsline{toc}{chapter}{Bibliography}\\markboth{Bibliography}{Bibliography}",
                  body, count=1)
    return body


# ============ Main driver ============

THESIS_MAIN_TEX = r"""% Auto-generated driver for the AITU memoir thesis template.
% Built by thesis/build_latex.py from the per-chapter Markdown sources.

\RequirePackage[l2tabu]{nag}
\let\ordinal\relax
\documentclass[a4paper,12pt,oneside,openbib,oldfontcommands]{memoir}

\usepackage{datetime}
\usepackage{ifpdf}
\ifpdf
\pdfinfo{
   /Author (Totin A., Aidarkhanov R., Sharipov B.)
   /Title (Development of a Deep Learning Model for Automated Tree Recognition and Green Space Mapping in Urban Environments)
   /Keywords (Astana; Tree Detection; YOLO; Mask R-CNN; DeepForest; SAM 2; Deep Learning; Remote Sensing)
}
\fi

\usepackage{microtype}
\sloppy

% A4 page layout (memoir-style, matches AITU template)
\settrimmedsize{297mm}{210mm}{*}
\setlength{\trimtop}{0pt}
\setlength{\trimedge}{\stockwidth}
\addtolength{\trimedge}{-\paperwidth}
\settypeblocksize{634pt}{448.13pt}{*}
\setulmargins{4cm}{*}{*}
\setlrmargins{*}{*}{1.5}
\setmarginnotes{17pt}{51pt}{\onelineskip}
\setheadfoot{\onelineskip}{2\onelineskip}
\setheaderspaces{*}{2\onelineskip}{*}
\checkandfixthelayout

\frenchspacing
\OnehalfSpacing

\setsecnumdepth{subsection}
\maxsecnumdepth{subsubsection}

\makepagestyle{myvf}
\makeoddfoot{myvf}{}{\thepage}{}
\makeevenfoot{myvf}{}{\thepage}{}
\makeevenhead{myvf}{\small\textsc{\leftmark}}{}{}
\makeoddhead{myvf}{}{}{\small\textsc{\rightmark}}
\pagestyle{myvf}

\newcommand{\clearemptydoublepage}{\newpage{\thispagestyle{empty}\cleardoublepage}}

% Use fontspec (xelatex) with a Unicode font that covers Latin + Cyrillic
% (including Kazakh-specific glyphs ғ ө ұ ң қ һ і) instead of T2A/T1 which
% miss several Kazakh letters.
\usepackage{fontspec}
\setmainfont{Times New Roman}
% Hyphenation in three languages via babel (no character mapping done by babel
% when fontspec is in use).
\usepackage[main=english, russian]{babel}
\babelprovide[import]{kazakh}

\usepackage{import}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{newlfont}
\usepackage{graphicx}
% Look for figures referenced as `figures/X.png` in markdown:
% - `figures/` resolves at the top-level (thesis/latex/figures/) for frontmatter \input
% - `../../figures/` resolves for chapters imported via \import{chapters/chapterNN/}{...}
\graphicspath{{figures/}{../figures/}{../../figures/}{logos/}}
% Default \includegraphics to fit the text width and preserve aspect ratio so
% large screenshots / multi-tile val_batch grids do not overflow the page.
\setkeys{Gin}{width=\linewidth,keepaspectratio}
\usepackage{float}
\usepackage{url}
\usepackage[colorlinks=true,allcolors=black]{hyperref}
\usepackage{memhfixc}
\usepackage{enumerate}
\usepackage{enumitem}
\usepackage{subcaption}
\usepackage{xcolor}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage{array}
\usepackage{calc}
\usepackage{etoolbox}

% Tighter list spacing (pandoc-friendly defaults are too loose)
\setlist[itemize]{itemsep=2pt, topsep=4pt}
\setlist[enumerate]{itemsep=2pt, topsep=4pt}

% Pandoc helpers
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\providecommand{\passthrough}[1]{#1}
% Defensive fallback for pandoc's image-wrapping macro (newer pandoc emits
% \pandocbounded around \includegraphics; older preambles like ours lack it).
\providecommand{\pandocbounded}[1]{#1}
% Pandoc emits `{\def\LTcaptype{none} ... \end{longtable}}` to suppress
% auto-captioning of longtables. The trick requires a `none` counter to exist;
% memoir doesn't define one, so we create a dummy.
\newcounter{none}
% Code-block environment expected by pandoc's LaTeX output (Shaded wraps
% Highlighting; we define a minimal shaded background).
\usepackage{framed}
\usepackage{fancyvrb}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}, fontsize=\small}
% Pandoc highlight tokens (NormalTok, KeywordTok, etc.) — define as no-ops
% so syntax-highlighted code compiles even without a colour scheme.
\providecommand{\NormalTok}[1]{#1}
\providecommand{\KeywordTok}[1]{\textbf{#1}}
\providecommand{\DataTypeTok}[1]{#1}
\providecommand{\DecValTok}[1]{#1}
\providecommand{\StringTok}[1]{#1}
\providecommand{\CommentTok}[1]{\textit{#1}}
\providecommand{\OperatorTok}[1]{#1}
\providecommand{\AttributeTok}[1]{#1}
\providecommand{\FunctionTok}[1]{#1}
\providecommand{\ControlFlowTok}[1]{\textbf{#1}}
\providecommand{\BuiltInTok}[1]{#1}
\providecommand{\OtherTok}[1]{#1}
\providecommand{\VariableTok}[1]{#1}
\providecommand{\SpecialCharTok}[1]{#1}
\providecommand{\PreprocessorTok}[1]{#1}
\providecommand{\WarningTok}[1]{\textbf{#1}}
\providecommand{\AlertTok}[1]{\textbf{#1}}
\providecommand{\ErrorTok}[1]{\textbf{#1}}
\providecommand{\InformationTok}[1]{#1}
\providecommand{\AnnotationTok}[1]{\textit{#1}}
\providecommand{\ConstantTok}[1]{#1}
\providecommand{\FloatTok}[1]{#1}
\providecommand{\BaseNTok}[1]{#1}
\providecommand{\CharTok}[1]{#1}
\providecommand{\SpecialStringTok}[1]{#1}
\providecommand{\VerbatimStringTok}[1]{#1}
\providecommand{\ImportTok}[1]{#1}
\providecommand{\DocumentationTok}[1]{#1}
\providecommand{\CommentVarTok}[1]{#1}
\providecommand{\ExtensionTok}[1]{#1}
\providecommand{\RegionMarkerTok}[1]{#1}

\widowpenalty=10000
\clubpenalty=10000

\begin{document}

\frontmatter
\pagenumbering{roman}

\input{frontmatter/title}

% Frontmatter order follows the AITU reference thesis:
% Abstract -> Dedication/Acknowledgements -> Declaration ->
% (Abbreviations, Definitions) -> List of Tables -> List of Figures ->
% Table of Contents.
\input{frontmatter/abstract}

\input{frontmatter/acknowledgements}

\input{frontmatter/declaration}

\input{frontmatter/abbreviations}

\input{frontmatter/definitions}

\listoftables
\clearpage

\listoffigures
\clearpage

\renewcommand{\contentsname}{Table of Contents}
\maxtocdepth{subsection}
\tableofcontents*
\clearpage

\input{frontmatter/intro.tex}

\mainmatter

\import{chapters/chapter01/}{introduction.tex}

\import{chapters/chapter02/}{main.tex}

\import{chapters/chapter03/}{conclusion.tex}

\input{frontmatter/concl.tex}

\backmatter
\input{chapters/appendices/references.tex}

\end{document}
"""


def main() -> None:
    if not TECTONIC.exists():
        sys.exit(f"tectonic not found at {TECTONIC}; install it first.")
    if not LATEX.exists():
        sys.exit(f"AITU template not unpacked at {LATEX}; "
                 f"copy from 'критериии и примеры/AITU_Diploma_2025-2026' first.")

    print("=== Reading Markdown sources ===")
    md = {p.stem: p.read_text(encoding="utf-8")
          for p in (sorted(HERE.glob("0?_*.md")) + sorted(HERE.glob("0?b_*.md"))
                    + sorted(HERE.glob("0?c_*.md")) + sorted(HERE.glob("0?a_*.md")))}
    for k in sorted(md):
        print(f"  {k}: {len(md[k]):,} chars")

    print("\n=== Generating LaTeX fragments ===")
    write(LATEX / "frontmatter" / "title.tex", make_title_tex())
    write(LATEX / "frontmatter" / "abstract.tex",
          make_abstract_tex(md["01_abstract"]))
    write(LATEX / "frontmatter" / "declaration.tex",
          make_declaration_tex(md["01b_declaration"]))
    write(LATEX / "frontmatter" / "acknowledgements.tex",
          make_acknowledgements_tex(md["00b_acknowledgements"]))
    write(LATEX / "frontmatter" / "abbreviations.tex",
          make_abbreviations_tex(md["01a_abbreviations"]))
    write(LATEX / "frontmatter" / "definitions.tex",
          make_definitions_tex(md["01c_definitions"]))
    write(LATEX / "frontmatter" / "intro.tex",
          make_intro_tex(md["02_intro"]))
    write(LATEX / "chapters" / "chapter01" / "introduction.tex",
          make_chapter_tex(HERE / "03_chapter1.md"))
    write(LATEX / "chapters" / "chapter02" / "main.tex",
          make_chapter_tex(HERE / "04_chapter2.md"))
    write(LATEX / "chapters" / "chapter03" / "conclusion.tex",
          make_chapter_tex(HERE / "05_chapter3.md"))
    write(LATEX / "frontmatter" / "concl.tex",
          make_concl_tex(md["06_conclusion"]))
    write(LATEX / "chapters" / "appendices" / "references.tex",
          make_references_tex(md["07_references"]))
    write(LATEX / "thesis_main.tex", THESIS_MAIN_TEX)

    # Mirror the markdown-side `thesis/figures/` directory into the LaTeX
    # build tree so that \includegraphics{figures/X.png} resolves both at the
    # top level (thesis/latex/figures/X.png via the `figures/` graphicspath
    # entry) and from within \import-ed chapters.
    src_figures = HERE / "figures"
    if src_figures.exists():
        dst_figures = LATEX / "figures"
        if dst_figures.exists():
            shutil.rmtree(dst_figures)
        shutil.copytree(src_figures, dst_figures)
        print(f"\n=== Mirrored {len(list(dst_figures.iterdir()))} figure(s) "
              f"into {dst_figures.relative_to(HERE)} ===")

    print("\n=== Compiling with tectonic ===")
    cmd = [str(TECTONIC), "--keep-logs", "--print",
           "--outdir", str(LATEX),
           str(LATEX / "thesis_main.tex")]
    print("  " + " ".join(cmd))
    result = subprocess.run(cmd, cwd=str(LATEX), capture_output=True,
                            text=True, encoding="utf-8", errors="replace")
    print(result.stdout[-3000:] if result.stdout else "")
    if result.returncode != 0:
        print("STDERR (last 4000 chars):", file=sys.stderr)
        print((result.stderr or "")[-4000:], file=sys.stderr)
        sys.exit(f"tectonic failed with code {result.returncode}")

    pdf = LATEX / "thesis_main.pdf"
    if pdf.exists():
        # Copy to thesis/thesis_latex.pdf for convenient access
        dst = HERE / "thesis_latex.pdf"
        shutil.copy(str(pdf), str(dst))
        print(f"\nWrote PDF: {dst} ({dst.stat().st_size:,} bytes)")
    else:
        sys.exit("tectonic produced no PDF")


if __name__ == "__main__":
    main()
